<?php
require_once("Views/Templates/heading.phtml");
?>

<body>
<!-- About IRIS Section -->
<section class="about-section">
    <div class="about-container">
        <div class="row">
            <div class="col-lg-12">
                <h1>About IRIS Software Group</h1>
                <p>IRIS Software Group is the UK’s largest privately owned software company. We specialize in producing award-winning mission-critical business software, including accounting, HR, and payroll solutions. Additionally, we develop software for the education sector.</p>
                <p>With 45 years of experience, IRIS has become a trusted partner for over 100,000 customers in more than 145 countries. Our commitment to innovation and excellence has made us a leader in the software industry.</p>
                <p>The purpose of this website is to showcase the carbon footprint of IRIS and the emissions produced based on our use of cloud technology.</p>
            </div>
        </div>
    </div>
</section>

</body>
</html>
<?php require('Templates/footer.phtml') ?>