<?php
require_once("Views/Templates/heading.phtml");
?>
<body>

<!-- Welcome Section -->
<section class="welcome-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h1>Welcome to IRIS</h1>
            </div>
        </div>
    </div>
</section>

<!-- Call-to-Action Section -->
<section class="cta-section">
    <div class="container">
        <p>Your Trusted Partner in Software Solutions <br>Transform your business with our innovative software solutions. <br>
            To view the level of CO2 emission that IRIS produces from our use of Cloud...</p>
    </div>
        <a href="loggedIn.php" class="btn btn-primary">Click here</a>
</section>

</body>
<?php require('Templates/footer.phtml') ?>