
<footer class="footer">
    <div class="foot-container">
        <span class="text-muted">Disclaimer:
            This website is a project created for academic purposes at the University of Salford under a hack camp. It is not an official website affiliated with or endorsed by IRIS. The content, information, and views presented here are solely for educational and demonstrative purposes and do not represent the views or policies of IRIS. All product names, logos, and brands appearing on this site are used for demonstration purposes only and remain the property of their respective owners.
        </span>
    </div>
</footer>
</body>
</html>

